#!/usr/bin/env ruby
require './app/caesarify.rb'

begin
  args = Caesarify::App::Config.parse_arguments
  app = Caesarify::App.new args
  app.run
rescue Caesarify::OptionsError
rescue Object => e
  puts e
end