---
caesarify:
        application_id: 4918cf3f34367f5102b0e82badbaa3b556eb5411cf22b12c7e296b65d0ac8501
        caesar_url: https://caesar-staging.zooniverse.org/
        doorkeeper_url: https://panoptes-staging.zooniverse.org/oauth/applications
        panoptes_url: https://panoptes-staging.zooniverse.org/
        secrets: secrets.yml
...
